### ISSUE TITLE
Uploads don't associate with existing DOIs.

### ISSUE THREAD

**Issue by johrstrom** [rseng/zenodo-release#1]
I'm trying this in a very simple project. But it seems when I upload the next version - the new DOI isn't associated with my existing DOI.

I'm trying to get the terminology right - but let's call it a base DOI. 

![image](https://user-images.githubusercontent.com/4874123/156812380-440b000c-1e17-43db-b908-ebd17fc6adc7.png)

https://zenodo.org/record/6325946 - is the link for version `2.0.23-1-1`, but somehow Zenodo was able to figure out it was associated with the base DOI https://doi.org/10.5281/zenodo.6323791

This is the base DOI i wanted to use (generated manually)
https://zenodo.org/record/6323748#.YiJLl9tOnzw

and this is the new DOI that isn't associated with the former (generated from https://github.com/johrstrom/test-actions).
https://zenodo.org/record/6328317#.YiJLsdtOnzw

**Comment by vsoch** [comment]
@johrstrom when I was testing I tried adding the .zenodo.json from a DOI that I created manually in the interface, and it gave me an error that I could not because it was "managed locally." So I think you'd have to create the record fully with the tool, but then update your .zendoo.json metadata record to use it. Do you want to try that?

**Comment by vsoch** [comment]
The deposition API has a doi field: 
![image](https://user-images.githubusercontent.com/814322/156818785-1e64f8c6-c01f-4ba4-a473-0279a3483186.png)
 so let's try adding it to that. If that works, we can update the action to have it and write instructions to the user to use it!

**Comment by johrstrom** [comment]
> The deposition API has a doi field

I think that's our ticket. I've got time today, so I was trying to work through it.  Happy to do it and submit a pull request.

**Comment by vsoch** [comment]
Sounds good! And I can help after the work day - we will get it working! Likely we need to give instruction to the user to have the field in the action blank, and then to add a doi field after the first push.

**Comment by vsoch** [comment]
okay this is fixed!
