### ISSUE TITLE
`set-output` is being deprecated 

### ISSUE THREAD

**Issue by johrstrom** [rseng/zenodo-release#7]
`set-output` is being deprecated. I see we use it here. A quick search doesn't seem to indicate it's anywhere else.

https://github.com/rseng/zenodo-release/blob/7c4c72db61b779416d12685fbd32daea31f77d4e/scripts/deploy.py#L193

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by vsoch** [comment]
Updated! let me know if there are any issues!

**Comment by johrstrom** [comment]
Thanks for the quick response! I'll update and let you know if there are any issues (no news being good news).
