### ISSUE TITLE
zenodo release failing with 404 can't find DOI

### ISSUE THREAD

**Issue by johrstrom** [rseng/zenodo-release#8]
Hi, I updated to the `main` branch to pick up an update, but the action is failing due to some 404 error. 

https://github.com/OSC/ondemand/actions/runs/7758926264/job/21161808177

It seems to be failing here, though it's not clear why (I'm guessing some Zenodo update?)

https://github.com/rseng/zenodo-release/blob/b12f099888f863857702b59985d45c8b32ca4032/scripts/deploy.py#L148-L155

I'll do some more digging and reply to this ticket with what I find.

**Comment by johrstrom** [comment]
There ended up being several issues here. I'll submit the patches shortly. I'll submit 1 PR with a few fixes or if you want to break them up into unique PRs for every issue that's fine with me too.

**Comment by vsoch** [comment]
One PR is good for me!
